services:
  gemini_bot:
    container_name: gemini-bot
    image: gemini-bot:latest
    hostname: gemini-bot       
    ports:
      - 8501:8501
    volumes:
      - /home/olonok_gmail_com/prompts/table:/home/app/gemini/prompts/table
      - /home/olonok_gmail_com/answers:/home/app/gemini/answers
      - /home/olonok_gmail_com/periciales/table:/home/app/gemini/pericial/table
      - /home/olonok_gmail_com/kb/docs:/home/app/gemini/kb/docs
      - /home/olonok_gmail_com/kb/chroma_db:/home/app/gemini/kb/chroma_db
      - /home/olonok_gmail_com/kb/faiss:/home/app/gemini/kb/faiss
    restart: always
    networks:
      - network
networks:
  network: