runtime: python
env: flex
entrypoint: streamlit run pages.py --server.port 8080
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11"

network:
  session_affinity: true

resources:
  cpu: 4
  memory_gb: 4
  disk_size_gb: 30